apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: dpsrv
  name: rc-refresh
spec:
  schedule: "*/1 * * * *"      # every 5 minutes
  concurrencyPolicy: Forbid     # prevent overlapping jobs
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pull
              image: maxfortun/private:alpine-tools-1
              command:
                - sh
                - -x
                - -c
                - |
                  cd /mnt/data/dpsrv/rc
                  git config --global --add safe.directory /mnt/data/dpsrv/rc
                  git config --local commit.gpgsign false
                  ls -la ~/.git-credentials
                  cat ~/.git-credentials
                  ls -la ~/.gitconfig
                  cat ~/.gitconfig
                  git pull -q
                  GIT_CHANGES=$(git status --porcelain |awk '{ print $2 }'|grep -v '/$')
                  if [ -n "$GIT_CHANGES" ]; then
                    git add $GIT_CHANGES
                    git commit -a -m updated
                    git push
                  fi
              volumeMounts:
                - name: data
                  mountPath: /mnt/data
                - name: git-credentials
                  mountPath: /root/.git-credentials
                  readOnly: true
                - name: git-openssl-salt
                  mountPath: /root/.config/git/openssl-salt
                  readOnly: true
                - name: git-openssl-password
                  mountPath: /root/.config/git/openssl-password
                  readOnly: true

          restartPolicy: OnFailure
          imagePullSecrets:
            - name: dockerhub-dpsrv
          volumes:
            - name: data
              hostPath:
                path: /mnt/data
                type: DirectoryOrCreate
            - name: git-credentials
              secret:
                secretName: git-credentials
            - name: git-openssl-salt
              secret:
                secretName: git-openssl-salt
            - name: git-openssl-password
              secret:
                secretName: git-openssl-password
