apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-sa
  namespace: dpsrv
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin   # ⚠️ full admin, restrict if possible
subjects:
- kind: ServiceAccount
  name: kubectl-sa
  namespace: dpsrv
---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
spec:
  serviceAccountName: kubectl-sa
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["sleep", "infinity"]

